services:
  app:
    image: caochientp1/chat-app
    env_file:
      - .env
    container_name: chat-app
    platform: linux/amd64
    restart: always
    ports:
      - "$PORT:$PORT"
    links:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      TZ: 'GMT'
      PGTZ: 'GMT'
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - 'db_data:/var/lib/postgresql/data'
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh

volumes:
  db_data:
    driver: local
